[versions]
#Configuration versions
javaCompileVersion = "VERSION_17"
jvmToolChainVersion = "17"

compileSdk = "36"
targetSdk = "36"
minSdk = "30"

#Dependency versions
activityCompose = "1.12.4"
adaptiveVersion = "1.2.0"
agp = "9.0.0"
assertj = "3.27.7"
coil = "2.7.0"
composeBom = "2026.01.01"
constraintLayout = "1.1.1"
coreKtx = "1.17.0"
coroutines = "1.10.2"
daggerHiltVersion = "2.59.1"
espressoCore = "3.7.0"
gsonVersion = "2.13.2"
jodaTimeVersion = "2.14.0"
junitBomVersion = "6.0.2"
hiltNavigationVersion = "1.3.0"
kotlin = "2.3.10"
kspVersion = "2.3.2"
lifecycleRuntimeKtx = "2.10.0"
loggingInterceptor = "5.3.2"
mockk = "1.14.9"
mockwebserverVersion = "5.3.2"
retrofit = "3.0.0"
store = "5.1.0-alpha08"
tracingVersion = "1.3.0"
turbine = "1.2.1"
windowCoreAndroid = "1.5.1"
uiTextGoogleFonts = "1.10.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

#Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintLayout" }
adaptive-layout = { group = "androidx.compose.material3.adaptive", name = "adaptive-layout", version.ref = "adaptiveVersion" }
adaptive-navigation = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation-android", version.ref = "adaptiveVersion" }

#Compose test
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

#Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "daggerHiltVersion" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "daggerHiltVersion" }
hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "daggerHiltVersion" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationVersion" }

#Retrofit
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }

logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "loggingInterceptor" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gsonVersion" }

coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
store = { group = "org.mobilenativefoundation.store", name = "store5", version.ref = "store" }
kotlinx-coroutines-core-jvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-jvm", version.ref = "coroutines" }

#Window size
androidx-window-core-android = { group = "androidx.window", name = "window-core-android", version.ref = "windowCoreAndroid" }
androidx-adaptive-android = { group = "androidx.compose.material3.adaptive", name = "adaptive-android", version.ref = "adaptiveVersion" }

# Test
coil-test = { group = "io.coil-kt", name = "coil-test", version.ref = "coil" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junitBomVersion" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-coroutines-test-jvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test-jvm", version.ref = "coroutines" }
mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "mockwebserverVersion" }
joda-time = { group = "joda-time", name = "joda-time", version.ref = "jodaTimeVersion" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "daggerHiltVersion" }
okhttp-tls = { group = "com.squareup.okhttp3", name = "okhttp-tls", version.ref = "mockwebserverVersion" }
androidx-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "daggerHiltVersion" }
tracing = { group = "androidx.tracing", name = "tracing", version.ref = "tracingVersion" }

[bundles]
junit-jupiter = ["junit-jupiter", "junit-jupiter-engine", "junit-platform-launcher"]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
daggerHiltPlugin = { id = "com.google.dagger.hilt.android", version.ref = "daggerHiltVersion" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }